/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n3.4-dev-2711-ge40fcb1"
#endif /* AVUTIL_FFVERSION_H */
